version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - jalyna
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.21.0
    - 5.21.1
    - 5.27.0
    - 5.29.0
    - 5.31.1
    - 5.35.0
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.1
    - 6.0.3
    - 7.0.0
  registries:
  - npm-registry-npm-pkg-github-com
